# Generated by Django 2.0 on 2018-12-20 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mixnet', '0005_valores'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='valores',
            name='n',
        ),
    ]
