# Generated by Django 2.0 on 2018-12-26 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mixnet', '0006_remove_valores_n'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asimetrico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p', models.CharField(default=0, max_length=20)),
            ],
        ),
    ]
